"""add last_backup_at to users

Adds a single nullable timestamp column ``last_backup_at`` to the ``users``
table — set by the email-backup service after a successful periodic backup
run. ``NULL`` means the user has never run a backup, which the scheduler
treats as "due as soon as backup_freq != 'never'".

Hand-written (not autogenerated) so the upgrade is idempotent on partially-
applied environments and the timezone-aware column type matches what the
ORM declares.

Revision ID: b8d4e2c91a05
Revises: c7f9b1e3a82d
Create Date: 2026-04-26
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = "b8d4e2c91a05"
down_revision: Union[str, Sequence[str], None] = "c7f9b1e3a82d"
branch_labels: Union[str, Sequence[str], None] = None
depends_on:    Union[str, Sequence[str], None] = None


_COLUMN_NAME = "last_backup_at"


def _user_columns(bind) -> set[str]:
    return {c["name"] for c in sa.inspect(bind).get_columns("users")}


def upgrade() -> None:
    bind = op.get_bind()
    if _COLUMN_NAME in _user_columns(bind):
        return
    op.add_column(
        "users",
        sa.Column(
            _COLUMN_NAME,
            sa.DateTime(timezone=True),
            nullable=True,
        ),
    )


def downgrade() -> None:
    bind = op.get_bind()
    if _COLUMN_NAME not in _user_columns(bind):
        return
    op.drop_column("users", _COLUMN_NAME)
