"""add user table and username fk to entry

Revision ID: ee363967b4c6
Revises: 0001
Create Date: 2026-04-05 14:03:44.364755

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ee363967b4c6'
down_revision: Union[str, Sequence[str], None] = '0001'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('entries', sa.Column('username', sa.String(length=100), nullable=False))
    op.create_index(op.f('ix_entries_username'), 'entries', ['username'], unique=False)
    op.create_foreign_key(None, 'entries', 'users', ['username'], ['username'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'entries', type_='foreignkey')
    op.drop_index(op.f('ix_entries_username'), table_name='entries')
    op.drop_column('entries', 'username')
    # ### end Alembic commands ###
