"""add user settings columns

Adds settings columns to the ``users`` table:

  * backup_freq               — periodic backup cadence (UI lands later)
  * default_sort              — preferred Library sort column (UI lands later)
  * default_entries_per_page  — preferred Library page size (UI lands later)
  * explore_default_medium    — default medium filter on the Explore page
  * explore_personalize       — toggle the Explore recommendation engine
  * explore_hide_in_library   — hide titles already in the user's library

Hand-written (not autogenerated) so the server-side defaults are explicit and
the upgrade is idempotent on partially-applied environments.

Revision ID: f152a6554320
Revises: ee363967b4c6
Create Date: 2026-04-25
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = "f152a6554320"
down_revision: Union[str, Sequence[str], None] = "ee363967b4c6"
branch_labels: Union[str, Sequence[str], None] = None
depends_on:    Union[str, Sequence[str], None] = None


# Columns added by this migration. Defined once so upgrade and downgrade
# stay in sync, and so the upgrade can iterate idempotently.
_NEW_COLUMNS = (
    sa.Column(
        "backup_freq",
        sa.String(length=20),
        nullable=False,
        server_default=sa.text("'never'"),
    ),
    sa.Column(
        "default_sort",
        sa.String(length=30),
        nullable=False,
        server_default=sa.text("'updated_at'"),
    ),
    sa.Column(
        "default_entries_per_page",
        sa.Integer(),
        nullable=False,
        server_default=sa.text("40"),
    ),
    sa.Column(
        "explore_default_medium",
        sa.String(length=50),
        nullable=True,
    ),
    sa.Column(
        "explore_personalize",
        sa.Boolean(),
        nullable=False,
        server_default=sa.text("true"),
    ),
    sa.Column(
        "explore_hide_in_library",
        sa.Boolean(),
        nullable=False,
        server_default=sa.text("true"),
    ),
)


def _existing_user_columns(bind) -> set[str]:
    insp = sa.inspect(bind)
    return {c["name"] for c in insp.get_columns("users")}


def upgrade() -> None:
    bind = op.get_bind()
    existing = _existing_user_columns(bind)
    for column in _NEW_COLUMNS:
        if column.name in existing:
            continue
        op.add_column("users", column)


def downgrade() -> None:
    bind = op.get_bind()
    existing = _existing_user_columns(bind)
    # Drop in reverse order for symmetry with upgrade.
    for column in reversed(_NEW_COLUMNS):
        if column.name not in existing:
            continue
        op.drop_column("users", column.name)
